### PR TITLE
initial commit. Barebones Scaffolding w/ placeholder elements

### PR DESCRIPTION
**Pull request by CampbellD84**

### CODE REVIEW

**Comment by nia-ja** [comment]
it's odd for the first PR in the repo, but it's a merge conflict you need to resolve first. Otherwise it looks good for me. Just DM me, when you resolve it and I will check your PR one more time. Good night!:)

**Comment by Levi-Huynh** [comment]
Main components; login/sign up forms, and component for teacher and classroom looks good.  Yes please let us know when conflicts are resolved for approval :)

**Comment by kyranmccann** [comment]
Any TL can merge and I’m online so... here!

**Comment by nia-ja** [comment]
Tnx, Kyran! You’re the best!

**Comment by CampbellD84** [comment]
Thank you!

**Pull request merged**
